// Unit checks for src/util. Run with: festina run tests/unit/test_util.f
import ../../src/util/color.f
import ../assert.f

check(asciiLower('HeLLo').toText() == 'hello', 'asciiLower')
check(asciiLower('plain') == 'plain', 'asciiLower no-op')
check(asciiIndexOf('a<b>c</b>', '</b>', 0) == 5, 'asciiIndexOf')
check(asciiIndexOf('abc', 'zz', 0) == -1, 'asciiIndexOf miss')
check(asciiIndexOfLower('A<STYLE>', '<style', 0) == 1, 'asciiIndexOfLower')
check(asciiStartsWith('hello', 'ell', 1), 'asciiStartsWith')
check(asciiEndsWith('rgb(1,2,3)', ')'), 'asciiEndsWith')
check(asciiTrim('  x y  ') == 'x y', 'asciiTrim')
check(asciiSplitChar('a, b,,c', CH_COMMA).length == 3, 'asciiSplitChar')
check(asciiSplitSpace('  one two   three ').length == 3, 'asciiSplitSpace')
parseNumberAt('12.5px', 0)
check(numOk && numValue == 12.5 && numEnd == 4, 'parseNumberAt')
parseNumberAt('-.5em', 0)
check(numOk && numValue == -0.5 && numEnd == 3, 'parseNumberAt leading dot')
parseNumberAt('auto', 0)
check(!numOk, 'parseNumberAt no digits')
check(parseFloatAscii(' 1.25 ') == 1.25, 'parseFloatAscii')
check(textLower('MiXed') == 'mixed', 'textLower')
check(repeatText('ab', 3) == 'ababab', 'repeatText')

int blk = COLOR_BLACK
check(parseCssColor('#000', blk) == COLOR_BLACK, 'hex #000')
check(parseCssColor('#FFFFFF', blk) == COLOR_WHITE, 'hex #ffffff')
check(parseCssColor('#336699', blk) == packColor(51, 102, 153, 255), 'hex #336699')
check(parseCssColor('#33669980', blk) == packColor(51, 102, 153, 128), 'hex with alpha')
check(parseCssColor('red', blk) == packColor(255, 0, 0, 255), 'named red')
check(parseCssColor('RebeccaPurple', blk) == packColor(102, 51, 153, 255), 'named case-insensitive')
check(parseCssColor('rgb(10, 20, 30)', blk) == packColor(10, 20, 30, 255), 'rgb()')
check(parseCssColor('rgba(10 20 30 / 0.5)', blk) == packColor(10, 20, 30, 128), 'rgba() slash syntax')
check(parseCssColor('rgb(100%, 0%, 50%)', blk) == packColor(255, 0, 128, 255), 'rgb() percent')
check(parseCssColor('hsl(120, 100%, 50%)', blk) == packColor(0, 255, 0, 255), 'hsl()')
check(parseCssColor('hsl(0 0% 100%)', blk) == COLOR_WHITE, 'hsl() white')
check(parseCssColor('transparent', blk) == COLOR_TRANSPARENT, 'transparent')
check(parseCssColor('currentColor', 12345) == 12345, 'currentcolor')
check(parseCssColor('bogus', blk) == COLOR_UNSET, 'unknown color')
check(colorRed(packColor(1, 2, 3, 4)) == 1 && colorGreen(packColor(1, 2, 3, 4)) == 2 && colorBlue(packColor(1, 2, 3, 4)) == 3 && colorAlpha(packColor(1, 2, 3, 4)) == 4, 'unpack')
check(colorWithOpacity(COLOR_BLACK, 0.5) == packColor(0, 0, 0, 128), 'colorWithOpacity')
finish('util')
